/* ===========================================================================
   Vedanta Spend Analytics — Azure SQL star schema
   ---------------------------------------------------------------------------
   Target : Azure SQL Database (also valid on SQL Server 2016+)
   Purpose: analytical store behind IDataProvider. Widgets send grouped
            aggregate queries, so both facts carry a clustered columnstore
            index and every descriptive attribute lives on a dimension.

   Grain
     fact_po_items  — one row per purchase-order line item (EKPO)
     fact_invoices  — one row per supplier-invoice line item (RSEG)

   Fiscal calendar
     Indian fiscal year, 1 April – 31 March. dim_date.fiscal_year holds the
     STARTING year: 25 Jan 2024 falls in FY 2023-24 → fiscal_year = 2023,
     fiscal_quarter = 4 (Jan–Mar), fiscal_period = 10 (April = period 1).

   Run order
     1. this file          — creates schema objects
     2. db/seed-data.sql   — generated by scripts/seed-azure-sql.ts

   Re-running is safe: every object is created only when absent. To rebuild
   from scratch, run the teardown block below first.
   =========================================================================== */

/* ---------------------------------------------------------------------------
   Teardown — uncomment to drop everything. Facts first: they hold the FKs.
   ---------------------------------------------------------------------------
DROP TABLE IF EXISTS dbo.snapshots;
DROP TABLE IF EXISTS dbo.fact_invoices;
DROP TABLE IF EXISTS dbo.fact_po_items;
DROP TABLE IF EXISTS dbo.dim_date;
DROP TABLE IF EXISTS dbo.dim_payment_terms;
DROP TABLE IF EXISTS dbo.dim_company;
DROP TABLE IF EXISTS dbo.dim_plant;
DROP TABLE IF EXISTS dbo.dim_material_category;
DROP TABLE IF EXISTS dbo.dim_vendor;
--------------------------------------------------------------------------- */

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ===========================================================================
   DIMENSIONS
   =========================================================================== */

-- Supplier master (LFA1/LFB1). parent_group_key rolls subsidiaries up to a
-- global ultimate so "spend by supplier group" is a single GROUP BY.
IF OBJECT_ID('dbo.dim_vendor', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_vendor
    (
        vendor_key          INT             IDENTITY(1, 1) NOT NULL,
        vendor_id           VARCHAR(10)     NOT NULL,
        vendor_name         NVARCHAR(100)   NOT NULL,
        -- NULL for suppliers that are their own ultimate parent.
        parent_group_key    VARCHAR(20)     NULL,
        parent_company_name NVARCHAR(100)   NULL,
        country             VARCHAR(3)      NULL,
        city                NVARCHAR(50)    NULL,
        tax_id              VARCHAR(20)     NULL,
        CONSTRAINT PK_dim_vendor PRIMARY KEY CLUSTERED (vendor_key),
        CONSTRAINT UQ_dim_vendor_vendor_id UNIQUE (vendor_id)
    );
END
GO

-- Material group (MATKL) with its two reporting levels. L1 is the executive
-- rollup ("Raw Materials"); L2 is the buyer-level leaf ("Zinc Concentrate").
IF OBJECT_ID('dbo.dim_material_category', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_material_category
    (
        category_key      INT           IDENTITY(1, 1) NOT NULL,
        material_group_id VARCHAR(10)   NOT NULL,
        category_l1_name  NVARCHAR(100) NOT NULL,
        category_l2_name  NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_dim_material_category PRIMARY KEY CLUSTERED (category_key),
        CONSTRAINT UQ_dim_material_category_group UNIQUE (material_group_id)
    );
END
GO

-- Plant / site (WERKS).
IF OBJECT_ID('dbo.dim_plant', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_plant
    (
        plant_key  INT           IDENTITY(1, 1) NOT NULL,
        plant_code VARCHAR(4)    NOT NULL,
        plant_name NVARCHAR(100) NOT NULL,
        country    VARCHAR(3)    NULL,
        CONSTRAINT PK_dim_plant PRIMARY KEY CLUSTERED (plant_key),
        CONSTRAINT UQ_dim_plant_plant_code UNIQUE (plant_code)
    );
END
GO

-- Legal entity / company code (BUKRS) — the consolidation boundary.
IF OBJECT_ID('dbo.dim_company', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_company
    (
        company_key  INT           IDENTITY(1, 1) NOT NULL,
        company_code VARCHAR(4)    NOT NULL,
        company_name NVARCHAR(100) NOT NULL,
        CONSTRAINT PK_dim_company PRIMARY KEY CLUSTERED (company_key),
        CONSTRAINT UQ_dim_company_company_code UNIQUE (company_code)
    );
END
GO

-- Payment terms (ZTERM). net_due_days drives the working-capital measures;
-- the discount_* pair is populated only for early-settlement terms
-- ("2% 10 Net 45" → discount_percent_1 = 2.00, discount_days_1 = 10).
IF OBJECT_ID('dbo.dim_payment_terms', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_payment_terms
    (
        payment_term_key   INT           IDENTITY(1, 1) NOT NULL,
        -- Wider than 4 chars: real term codes reach 9 ("D15N10N30"), and
        -- truncating would collide NET15 with NET150.
        term_code          VARCHAR(10)   NOT NULL,
        term_description   NVARCHAR(100) NOT NULL,
        net_due_days       INT           NULL,
        discount_days_1    INT           NULL,
        discount_percent_1 DECIMAL(5, 2) NULL,
        CONSTRAINT PK_dim_payment_terms PRIMARY KEY CLUSTERED (payment_term_key),
        CONSTRAINT UQ_dim_payment_terms_term_code UNIQUE (term_code)
    );
END
GO

-- Calendar, keyed YYYYMMDD so a fact's date key is readable without a join.
-- Fiscal columns follow the Indian April–March year (see header).
IF OBJECT_ID('dbo.dim_date', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_date
    (
        date_key        INT         NOT NULL,
        full_date       DATE        NOT NULL,
        [year]          INT         NOT NULL,
        [quarter]       INT         NOT NULL,
        [month]         INT         NOT NULL,
        month_name      VARCHAR(10) NOT NULL,
        fiscal_year     INT         NOT NULL,
        fiscal_quarter  INT         NOT NULL,
        fiscal_period   INT         NOT NULL,
        CONSTRAINT PK_dim_date PRIMARY KEY CLUSTERED (date_key),
        CONSTRAINT UQ_dim_date_full_date UNIQUE (full_date),
        CONSTRAINT CK_dim_date_quarter        CHECK ([quarter] BETWEEN 1 AND 4),
        CONSTRAINT CK_dim_date_month          CHECK ([month] BETWEEN 1 AND 12),
        CONSTRAINT CK_dim_date_fiscal_quarter CHECK (fiscal_quarter BETWEEN 1 AND 4),
        CONSTRAINT CK_dim_date_fiscal_period  CHECK (fiscal_period BETWEEN 1 AND 12)
    );
END
GO

/* ===========================================================================
   FACTS

   No surrogate primary key: a clustered columnstore index is the storage
   structure, and a PK would add a nonclustered B-tree that the analytical
   query pattern never uses. Re-seeding stays idempotent because
   db/seed-data.sql clears both facts before inserting.
   =========================================================================== */

-- Purchase-order line items (EKKO ⋈ EKPO). Deleted lines (LOEKZ) are removed
-- upstream by the ETL, so every row here is a live commitment.
IF OBJECT_ID('dbo.fact_po_items', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.fact_po_items
    (
        -- Dimension keys
        vendor_key           INT           NOT NULL,
        category_key         INT           NOT NULL,
        plant_key            INT           NOT NULL,
        company_key          INT           NOT NULL,
        po_date_key          INT           NOT NULL,
        -- Degenerate dimensions: the document identity itself
        po_number            VARCHAR(10)   NOT NULL,
        po_item_number       INT           NOT NULL,
        -- Measures. _doc is the document currency, _inr the reporting currency;
        -- only _inr is safe to sum across a mixed-currency population.
        net_order_value_doc  DECIMAL(18, 2) NOT NULL,
        net_order_value_inr  DECIMAL(18, 2) NOT NULL,
        currency_code        VARCHAR(3)     NOT NULL,
        po_quantity          DECIMAL(18, 3) NOT NULL,
        unit_price           DECIMAL(18, 2) NULL,
        is_contract_backed   BIT            NOT NULL CONSTRAINT DF_fact_po_items_contract DEFAULT (0),
        CONSTRAINT FK_fact_po_items_vendor
            FOREIGN KEY (vendor_key)   REFERENCES dbo.dim_vendor (vendor_key),
        CONSTRAINT FK_fact_po_items_category
            FOREIGN KEY (category_key) REFERENCES dbo.dim_material_category (category_key),
        CONSTRAINT FK_fact_po_items_plant
            FOREIGN KEY (plant_key)    REFERENCES dbo.dim_plant (plant_key),
        CONSTRAINT FK_fact_po_items_company
            FOREIGN KEY (company_key)  REFERENCES dbo.dim_company (company_key),
        CONSTRAINT FK_fact_po_items_po_date
            FOREIGN KEY (po_date_key)  REFERENCES dbo.dim_date (date_key)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CCI_fact_po_items'
                 AND object_id = OBJECT_ID('dbo.fact_po_items'))
BEGIN
    CREATE CLUSTERED COLUMNSTORE INDEX CCI_fact_po_items ON dbo.fact_po_items;
END
GO

-- Supplier invoice line items (RBKP ⋈ RSEG). Credit memos are stored with
-- negative amounts by the ETL, so SUM() nets them off without a CASE.
IF OBJECT_ID('dbo.fact_invoices', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.fact_invoices
    (
        -- Dimension keys
        vendor_key          INT            NOT NULL,
        category_key        INT            NOT NULL,
        plant_key           INT            NOT NULL,
        company_key         INT            NOT NULL,
        -- NULL when the supplier master carries no default term.
        payment_term_key    INT            NULL,
        -- Ledger date (drives period reporting) and the supplier's own
        -- document date (drives ageing). Both resolve against dim_date.
        posting_date_key    INT            NOT NULL,
        invoice_date_key    INT            NOT NULL,
        -- Degenerate dimensions
        invoice_number      VARCHAR(10)    NOT NULL,
        fiscal_year         INT            NOT NULL,
        invoice_item_number INT            NOT NULL,
        -- Reference back to the commitment; not an FK, since invoices arrive
        -- against purchase orders outside the loaded window.
        po_number           VARCHAR(10)    NULL,
        po_item_number      INT            NULL,
        -- Measures
        gross_amount_doc    DECIMAL(18, 2) NOT NULL,
        gross_amount_inr    DECIMAL(18, 2) NOT NULL,
        net_amount_inr      DECIMAL(18, 2) NOT NULL,
        currency_code       VARCHAR(3)     NOT NULL,
        is_credit_memo      BIT            NOT NULL CONSTRAINT DF_fact_invoices_credit_memo DEFAULT (0),
        payment_block_flag  BIT            NOT NULL CONSTRAINT DF_fact_invoices_payment_block DEFAULT (0),
        CONSTRAINT FK_fact_invoices_vendor
            FOREIGN KEY (vendor_key)       REFERENCES dbo.dim_vendor (vendor_key),
        CONSTRAINT FK_fact_invoices_category
            FOREIGN KEY (category_key)     REFERENCES dbo.dim_material_category (category_key),
        CONSTRAINT FK_fact_invoices_plant
            FOREIGN KEY (plant_key)        REFERENCES dbo.dim_plant (plant_key),
        CONSTRAINT FK_fact_invoices_company
            FOREIGN KEY (company_key)      REFERENCES dbo.dim_company (company_key),
        CONSTRAINT FK_fact_invoices_payment_term
            FOREIGN KEY (payment_term_key) REFERENCES dbo.dim_payment_terms (payment_term_key),
        CONSTRAINT FK_fact_invoices_posting_date
            FOREIGN KEY (posting_date_key) REFERENCES dbo.dim_date (date_key),
        CONSTRAINT FK_fact_invoices_invoice_date
            FOREIGN KEY (invoice_date_key) REFERENCES dbo.dim_date (date_key)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CCI_fact_invoices'
                 AND object_id = OBJECT_ID('dbo.fact_invoices'))
BEGIN
    CREATE CLUSTERED COLUMNSTORE INDEX CCI_fact_invoices ON dbo.fact_invoices;
END
GO

/* ===========================================================================
   APPLICATION TABLES
   =========================================================================== */

-- Saved dashboard view states ("cloud snapshots"): the filters, thresholds, and
-- widget configuration a user had on screen, serialized as JSON. Deliberately
-- NOT part of the star schema and carries no foreign keys — dashboard_id names
-- either a core route key ("tail-spend") or a custom dashboard's browser-side
-- id, neither of which exists as a dimension. Rowstore, OLTP access pattern:
-- point INSERTs and a per-dashboard timeline read.
IF OBJECT_ID('dbo.snapshots', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.snapshots
    (
        -- UUID minted by the API route, never client-supplied.
        id            VARCHAR(36)    NOT NULL,
        name          NVARCHAR(255)  NOT NULL,
        dashboard_id  NVARCHAR(100)  NOT NULL,
        created_at    DATETIME2      NOT NULL CONSTRAINT DF_snapshots_created_at DEFAULT GETDATE(),
        created_by    NVARCHAR(100)  NOT NULL CONSTRAINT DF_snapshots_created_by DEFAULT N'local-user',
        -- JSON payload of metrics, filters, and widget states.
        snapshot_data NVARCHAR(MAX)  NOT NULL,
        CONSTRAINT PK_snapshots PRIMARY KEY CLUSTERED (id)
    );
END
GO

-- The timeline query: WHERE dashboard_id = @p ORDER BY created_at DESC.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_snapshots_dashboard_created'
                 AND object_id = OBJECT_ID('dbo.snapshots'))
BEGIN
    CREATE NONCLUSTERED INDEX IX_snapshots_dashboard_created
        ON dbo.snapshots (dashboard_id, created_at DESC);
END
GO
